# Generated by Django 4.1.8 on 2023-04-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSubmittedAnswer',
        ),
    ]
