# Generated by Django 4.1.8 on 2023-04-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_usersubmittedanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmittedanswer',
            name='right_answer',
        ),
    ]
