# Generated by Django 4.1.8 on 2023-04-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_remove_usersubmittedanswer_right_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmittedanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='usersubmittedanswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='questions',
        ),
        migrations.DeleteModel(
            name='UserSubmittedAnswer',
        ),
    ]
