# Generated by Django 4.1.8 on 2023-04-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_attempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField()),
                ('total_skipped', models.IntegerField()),
                ('total_attempted', models.IntegerField()),
                ('right_answers', models.IntegerField()),
                ('percentage', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Score',
            },
        ),
    ]
